name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: dandori-team-one
  REGION: europe-west1
  SERVICE: dandori
  REPOSITORY: rag-repo
  WORKLOAD_IDENTITY_PROVIDER: projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
  SERVICE_ACCOUNT: github-deployer@dandori-team-one.iam.gserviceaccount.com


jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/992215387767/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-deployer@dandori-team-one.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy dandori-team-one-git \
            --source . \
            --region europe-west1 \
            --allow-unauthenticated \
            --memory=1Gi \
            --concurrency=1 \
            --set-env-vars GCP_PROJECT_ID=dandori-team-one